#!/bin/bash
## cleanup
## version 0.0.1 - initial
##################################################
. ${SH2}/cecho.sh
. ${SH2}/store.sh
. ${SH2}/aliases/commands.sh
shopt -s expand_aliases
alias bind-variables='
{
  local -i score_prior
}
'
score-show() {
  local -i score_now
  score_now=$( store get score )
  test ! ${score_prior} -lt ${score_now} || {
    cecho yellow "score now ${score_now} (+$( score increase ))"
  }
}
score-increase() {
  local -i score_increase
  let score_increase=score_now-score_prior 
  echo "${score_increase}"
}
score() {
  commands
}
make-directory() {
  test -d "${1}" || {
    cecho yellow "$( mkdir -pv ${_} )"
    store incr score 1
  }
}
find-needle-files() {
  find-files "${needle}"
}
find-files() { { local needle ; needle="${1}" ; }
  find . -mindepth 1 -maxdepth 1 -type f -name "${needle}"
}
find-and-move() { { local needle ; needle="${1}" ; local dest ; dest="${2}" ; }
  local -i move_count
  test -d "./${dest}" || return
  move_count=$( find-needle-files | wc -l )
  test ${move_count} -gt 0 || return
  cecho green "| moving ${move_count} files to ${dest} ..."
  test "${dryrun:-false}" = "true" && { 
    find-needle-files | xargs -i echo mv -vi {} ${dest}/
  } || {
    find-needle-files | xargs -i mv -vi {} ${dest}/
    store incr score ${move_count}
  }
  
  cecho green "| done"
}
cleanup() {
  commands
}
##################################################
## generated by create-stub2.sh v0.1.2
## on Mon, 22 Jun 2020 14:44:59 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
