#!/bin/bash
## getops
## version 0.0.2 - using seq
##################################################
on-shortops-case() {
 case ${1} in
  t) {
   option_test="true"
   echo 1
  } ;;
  v) {
   option_variable="${2}"
   echo 2
  } ;;
 esac
}
#-------------------------------------------------
on-shortops() {
 str_length() { { local str ; str=${@} ; }
  echo ${str} | wc -c
 }
 #echo ${1} 1>&2
 local i
 for i in $( seq $(( $( str_length ${1:1} ) - 1 )) )
 do
  #echo ${1:${i}:1} 1>&2
  ${FUNCNAME}-case ${1:${i}:1} ${2}
 done
}
#-------------------------------------------------
on-longops() {
 #echo ${@} 1>&2
 echo 1 # shift 1
}
#-------------------------------------------------
getops() {
 while [ ${#} -gt 0 ]
 do
  case ${1} in 
   --) { # terminate all options 
    true # end of options
    break
   } ;;
   -*-) {
    false || {
     error "malformed short option" "${FUNCNAME}" "${LINENO}"
     false
    }
   } ;;
   --*) {
    on-longops $( echo ${@} | sed -e 's/--//' ) 1>/dev/null
    shift $( on-longops $( echo ${@} | sed -e 's/--//' ) )
    continue
   } ;;
   -*) {
    on-shortops ${@} &>/dev/null
    shift $( on-shortops ${@} )
    continue
   } ;; 
   *) { # not an option
    true
   } ;;
  esac 
  #echo ${#}
  shift
  sleep 1
 done
}
##################################################
## generated by create-stub2.sh v0.1.1
## on Mon, 11 Jun 2018 22:38:41 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
