#!/bin/bash
## getops
## version 0.0.2 - nocompound shortop
##################################################
on-shortops-case() {
 case ${1} in
  t) {
   option_test="true"
   echo 1
  } ;;
  v) {
   option_variable="${2}"
   echo 2
  } ;;
 esac
}
#-------------------------------------------------
on-shortops() { 
 ${FUNCNAME}-case ${1:1:1} ${@:2}
}
#-------------------------------------------------
on-longops() {
 #echo ${@} 1>&2
 echo 1 # shift 1
}
#-------------------------------------------------
getops() {
 while [ ${#} -gt 0 ]
 do
  case ${1} in 
   --) { # terminate all options 
    true # end of options
    break
   } ;;
   -*-) {
    false || {
     error "malformed short option" "${FUNCNAME}" "${LINENO}"
     false
    }
   } ;;
   --*) {
    on-longops $( echo ${@} | sed -e 's/--//' ) 1>/dev/null
    shift $( on-longops $( echo ${@} | sed -e 's/--//' ) )
    continue
   } ;;
   -*) {
    on-shortops ${@} 1>/dev/null
    shift $( on-shortops ${@} )
    continue
   } ;; 
   *) { # not an option
    true
   } ;;
  esac 
  #echo ${#}
  shift
  sleep 1
 done
}
##################################################
#if [ ${#} -eq 0 ] 
#then
# true
#else
# exit 1 # wrong args
#fi
##################################################
#getops
##################################################
## generated by create-stub2.sh v0.1.1
## on Mon, 11 Jun 2018 22:38:41 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
