#!/bin/bash
## history
## - easier to use history command
## version 0.0.3 - execute-patterns
## to do:
## - only show real history line numbers
##################################################
. $( dirname ${0} )/error.sh
_cleanup() {
 _() {
   {
     test ! -f "${1}" || {
       cecho yellow $( rm -v ${1} ) 
     }
   } &>/dev/null 
 }
 _ "temp-history-1"
 _ "temp-history-2"
}
#-------------------------------------------------
. $( dirname ${0} )/aliases/commands.sh
#-------------------------------------------------
cecho() { $( dirname ${0} )/cecho.sh ${@} ; }
car() { $( dirname ${0} )/car.sh ${@} ; }
cdr() { $( dirname ${0} )/cdr.sh ${@} ; }
#-------------------------------------------------
## testing (1)
_history-grep-for-each-pattern-do() { #{ local patterns ; patterns=${@} ; }
 echo -n "| grep "
 echo -n "-"
 echo -n "e \"${pattern}\" "
}
## testing (1)
_history-grep-for-each-pattern() { #{ local patterns ; patterns=${@} ; }
 {
   local pattern
   for pattern in ${patterns}
   do
    ${FUNCNAME}-do
   done 
 } | sed '1s/^.//'
}
_history-grep-setup-patterns() { 
 pattern=$( car ${patterns} )
 cecho yellow pattern: ${pattern}
 cecho yellow patterns: ${patterns}
 patterns=$( cdr ${patterns} || true )
}
_history-grep-execute-patterns() { 
  cecho green in ${FUNCNAME}

  {
    {
      gawk -e "/${pattern}/{print NR \" \" \$(0)}" temp-history-1
    } | tee temp-history-2 
  } 1>&2
  cecho yellow $( cp -v temp-history-2 temp-history-1 )
}
_history-grep() { { local patterns ; patterns=${@} ; } 
  ## testing (1)
  #echo $( ${FUNCNAME}-for-each-pattern ) 
  #return 
  #{ 
  #  {
  #    cat ~/.bash_history 
  #  } \
  #  | gawk '{print NR " " $(0)}' \
  #  | grep -e "${patterns}" 
  #}

  cecho yellow $( cp -v  ~/.bash_history temp-history-1 )
  cecho yellow $( cp -v  temp-history-1 temp-history-2 )
  {
    tail temp-history-1 
  } 1>&2

  local pattern 
  while [ ! ]
  do
   test "${patterns}" || { break ; }
   ${FUNCNAME}-setup-patterns
   ${FUNCNAME}-execute-patterns
   continue
  done

  cat temp-history-1

}
_history-last() { { local patterns ; patterns=${@} ; } 
  {
    _history-grep ${patterns}
  } | sed -n '$p'
}
_history() {  
  {
    commands 
  } 2>/dev/null
}
##################################################
if [ ! ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
_history ${@}
##################################################
## generated by create-stub2.sh v0.1.1
## on Mon, 07 May 2018 08:29:04 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
