#!/bin/bash
## history
## - easier to use history command
## =stub=
## version 0.0.0 - stub
exit 0
##################################################
history() {
 true
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
history
##################################################
## generated by create-stub2.sh v0.1.1
## on Mon, 07 May 2018 08:29:04 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
