#!/bin/bash
## history
## - easier to use history command
## version 0.0.2 - grep initial
##################################################
car() { $( dirname ${0} )/car.sh ${@} ; }
cdr() { $( dirname ${0} )/cdr.sh ${@} ; }
. $( dirname ${0} )/aliases/commands.sh
## testing (1)
_history-grep-for-each-pattern-do() { #{ local patterns ; patterns=${@} ; }
 echo -n "| grep "
 echo -n "-"
 echo -n "e \"${pattern}\" "
}
## testing (1)
_history-grep-for-each-pattern() { #{ local patterns ; patterns=${@} ; }
 {
   local pattern
   for pattern in ${patterns}
   do
    ${FUNCNAME}-do
   done 
 } | sed '1s/^.//'
}
_history-grep() { { local patterns ; patterns=${@} ; } 
　## testing (1)
  #echo $( ${FUNCNAME}-for-each-pattern ) 
  #return 
  { 
    {
      cat ~/.bash_history 
    } \
    | gawk '{print NR " " $(0)}' \
    | grep -e "${patterns}" 
  }
}
_history-last() { { local patterns ; patterns=${@} ; } 
  {
    _history-grep "${patterns}"
  } | sed -n '$p'
}
_history() {
 commands
}
##################################################
if [ ! ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
_history ${@}
##################################################
## generated by create-stub2.sh v0.1.1
## on Mon, 07 May 2018 08:29:04 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
