#!/bin/bash
## _test
## version 0.0.1 - initial
##################################################
. $( dirname ${0} )/aliases/commands.sh
. $( dirname ${0} )/cecho.sh
. $( dirname ${0} )/error.sh	# error handling
#-------------------------------------------------
_test-error() {
 
 cecho green testing error ...

 cecho green using default, hide errors

 cecho green causing error ...

 false || {
  cecho yellow error hidden
  #false
 }

 cecho green setting to show errors

 error "true" # show error

 cecho green causing error ...

 false || {
  cecho yellow error shown
  error "manual error" "${FUNCNAME}" "${LINENO}"
  false
 }

 true

}
#-------------------------------------------------
_test() {
  {
    commands 
  } 
}
##################################################
if [ ! ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
_test ${@}
##################################################
## generated by create-stub2.sh v0.1.1
## on Mon, 07 May 2018 21:36:52 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
