#!/bin/bash
## worker
## version 0.0.1 - initial
##################################################
worker() { { local infile ; infile="${1}" ; local -i concurrency ; concurrency="${2-1}" ; }
  if-concurrency() {
    test ! ${concurrency} -gt 1 || {
      echo "-P ${concurrency}"
      cecho yellow "concurrency: ${concurrency}"
    }
  }
  cecho green "doing work on $( cat ${infile} | wc -l ) jobs ..."
  time { 
    cat ${infile} | 
    xxd -ps | 
    sed 's/0a/00/g' | 
    xxd -ps -r | 
    xargs $( if-concurrency ) -0 -i bash ${0} {}
  }
  cecho green "done doing work"
}
##################################################
## generated by create-stub2.sh v0.1.2
## on Wed, 17 Jul 2019 13:36:48 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
